
package ru.clevertec.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductServiceImpl", targetNamespace = "http://service.clevertec.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductServiceImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ru.clevertec.service.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://service.clevertec.ru/", className = "ru.clevertec.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.clevertec.ru/", className = "ru.clevertec.service.AddResponse")
    @Action(input = "http://service.clevertec.ru/ProductServiceImpl/addRequest", output = "http://service.clevertec.ru/ProductServiceImpl/addResponse")
    public Product add(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.clevertec.service.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://service.clevertec.ru/", className = "ru.clevertec.service.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://service.clevertec.ru/", className = "ru.clevertec.service.FindByIdResponse")
    @Action(input = "http://service.clevertec.ru/ProductServiceImpl/findByIdRequest", output = "http://service.clevertec.ru/ProductServiceImpl/findByIdResponse")
    public Product findById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
